### ISSUE TITLE
System.Drawing.SafeNativeMethods.Gdip

### ISSUE THREAD

**Issue by jdbogdan** [barnhill/barcodelib#168]
at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit)
   at BarcodeLib.Barcode..ctor()
   at UIH.Rt.Emr.DomainService.ReportTemplate.Utils.PrintDataFactory.GetBarcodeBase64Async(String patientId) in /app/wemr/src/UIH.Rt.Emr.Domain/DomainService/ReportTemplate/Utils/PrintDataFactory.cs:line 2473
   at UIH.Rt.Emr.DomainService.ReportTemplate.Utils.PrintDataFactory.CreatePatientPrintData(PatientInformationEntity patient, List`1 patientRisks) in /app/wemr/src/UIH.Rt.Emr.Domain/DomainService/ReportTemplate/Utils/PrintDataFactory.cs:line 235

**Comment by barnhill** [comment]
I dont see anything in this stacktrace that points to the barcode library.  With version 3.0 the reference to System.Drawing was removed and maybe your application needs that reference?
